languages:
  PHP: true
plugins:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  sonar-php:
    enabled: true
ratings:
  paths:
    - src/**
exclude_paths:
  - test/**/*
  - vendor/**/*
  - resoufces/**/*
  - config/**/*
