languages:
  PHP: true
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
ratings:
  paths:
    - src/**
exclude_paths:
  - test/**/*
  - vendor/**/*
  - resoufces/**/*
  - config/**/*
